services:
  - type: web
    name: asset-manager
    env: node
    plan: free
    buildCommand: npm ci && npm run render:build
    startCommand: npm run render:start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
